version: "3"

networks:
  gitea:
    external: false

# volumes:
#   gitea:
#     driver: local
#   # mysql:
#   #   driver: local
#   postgres:
#       driver: local

services:
  gitea:
    image: gitea/gitea:${GITEA_VERSION}
    environment:
      - USER=git
      - USER_UID=1000
      - USER_GID=1000
      # - GITEA__database__DB_TYPE=mysql
      # - GITEA__database__HOST=db:3306
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea 
    restart: always
    networks:
      - gitea
    volumes:
      # - gitea:/data
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  # db:
  #   image: mysql:${MYSQL_VERSION}
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=gitea
  #     - MYSQL_USER=gitea
  #     - MYSQL_PASSWORD=gitea
  #     - MYSQL_DATABASE=gitea
  #   networks:
  #     - gitea
  #   volumes:
  #     # - mysql:/var/lib/mysql
  #     - ./mysql:/var/lib/mysql
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      # - postgres:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data